version: '3.4'
services:
  nodeshark:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:5050
    environment:
      - PORT=5050 # over riding defaults in image.
# over riding defaults does not mean changes are made to image.
# copy-on-write
# overriden changes go to thin writable layer attached to the container.
    #command: sleep 300